newline

diff --git a/docker/docker-compose.dev.yml b/docker/docker-compose.dev.yml
--- a/docker/docker-compose.dev.yml
+++ b/docker/docker-compose.dev.yml
@@ -129,7 +129,8 @@ services:
         pg_isready --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" || exit 1;
         Chksum="$$(psql --dbname="$${POSTGRES_DB}" --username="$${POSTGRES_USER}" --tuples-only --no-align
         --command='SELECT COALESCE(SUM(checksum_failures), 0) FROM pg_stat_database')";
-        echo "checksum failure count is $$Chksum"; [ "$$Chksum" = '0' ] || exit 1
+        echo "checksum failure count is $$Chksum"
+        [ "$$Chksum" = '0' ] || exit 1
       interval: 5m
       start_interval: 30s
       start_period: 5m
